Random Agent
mdkdoc15/group_1_cse_491 pull request #10
Opened 2023-11-07 20:33 UTC by GoldenMurrani

Agent that walks randomly based on seed from world

2023-11-07 22:38 UTC, Kanakmk approved these changes
The Random Agent looks good!

2023-11-08 18:04 UTC, mdkdoc15 requested changes
Agent looks good, there seems to be a lot of build files that should be removed, Additionally unsure if the Item Inventory need to be included

2023-11-08 18:04 UTC, mdkdoc15 commented on tests/build/CMakeCache.txt
Im unsure if all these files need to be here, due to the fact they are build files

2023-11-08 18:04 UTC, mdkdoc15 commented on source/core/AgentBase.hpp
do we want this inventory class? I think the prof was implementing it on his own. If that is the case then we should remove all files associated with the inventory

2023-11-14 01:06 UTC, mdkdoc15 approved these changes
Changes made looks good

2023-11-14 01:11 UTC, merged